name: lighthouse
on:
  push:
    branches:
      - develop
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install packages
        run: yarn install --frozen-lockfile
      - name: build
        run: yarn build
      - name: run Lighthouse CI
        run: |
          yarn global add @lhci/cli@0.6.x
          lhci autorun
